###服务启动端口号
server:
  port: 8100
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-entry-sevice
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8000/eureka
###注册到注册中心
    register-with-eureka: true
###是否需要从eureka上获取注册信息
    fetch-registry: true